In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="white")
import os
import plotly.express as px
from plotly.subplots import make_subplots
from plotly import graph_objects as go
import warnings
warnings.filterwarnings("ignore")

In [4]:
controllers= ["disparity_extender","pure_pursuit","e2e"]
opponents = [2,3]
obstacles = [0,5]

original_dfs = []
file_str = "nosimplex_{}_1.000000_{}_{}_0.0_0.0.csv"
collision_str = "nosimplex_collisions_{}_{}_{}_0.0_0.0_cones.csv"

for cntrl in controllers:
    for opp in opponents:
        for obs in obstacles:
            fh = file_str.format(cntrl,opp,obs)
            ch = collision_str.format(cntrl,opp,obs)
            
            
            df = pd.read_csv(fh,header=None)
            df =df.rename(columns={0:'time_str',1:'time_taken_lec',2:'time_taken_safety_controller',3:'area'})
            df['controller'] = cntrl
            
            df['time_taken_lec'] = df['time_taken_lec'] * 100
            df['number_of_opponents'] = opp
            
            df['number_of_obstacles']= obs
            
            if(os.path.exists(ch)):
                c_df = pd.read_csv(ch,header=None)
                df['collision_percentage'] = ((c_df.count()[0])/10)*100
            else:
                df['collision_percentage'] = 0.0
            
            df = df.drop(columns = ["time_taken_safety_controller","area"])
            
            original_dfs.append(df)
            
dfs = pd.concat(original_dfs)
dfs

,time_str,time_taken_lec,controller,number_of_opponents,number_of_obstacles,collision_percentage
0,28/03/2022/17:06:42,82.6468,disparity_extender,2,0,0.0
1,28/03/2022/17:08:52,80.9925,disparity_extender,2,0,0.0
2,28/03/2022/17:11:00,81.3758,disparity_extender,2,0,0.0
3,28/03/2022/17:13:11,82.8485,disparity_extender,2,0,0.0
4,28/03/2022/17:15:22,79.2029,disparity_extender,2,0,0.0
...,...,...,...,...,...,...
5,28/03/2022/16:51:42,99.4941,e2e,3,5,0.0
6,28/03/2022/16:54:56,97.0187,e2e,3,5,0.0
7,28/03/2022/16:58:11,95.8298,e2e,3,5,0.0
8,28/03/2022/17:01:22,97.9883,e2e,3,5,0.0
9,28/03/2022/17:04:32,99.4078,e2e,3,5,0.0

In [5]:
dfs.groupby(["controller","number_of_opponents","number_of_obstacles"]).median()

                                                            time_taken_lec  \
controller         number_of_opponents number_of_obstacles
disparity_extender 2                   0                          81.48825
                                       5                          80.54760
                   3                   0                          79.39895
                                       5                          80.84575
e2e                2                   0                          15.51720
                                       5                          80.40575
                   3                   0                          98.89785
                                       5                          97.86725
pure_pursuit       2                   0                         100.00000
                                       5                          94.48250
                   3                   0                          96.62175
                                       5                          94.23355

                                                            collision_percentage
controller         number_of_opponents number_of_obstacles
disparity_extender 2                   0                                     0.0
                                       5                                     0.0
                   3                   0                                     0.0
                                       5                                     0.0
e2e                2                   0                                   100.0
                                       5                                   100.0
                   3                   0                                     0.0
                                       5                                     0.0
pure_pursuit       2                   0                                     0.0
                                       5                                    20.0
                   3                   0                                     0.0
                                       5                                    30.0